### ISSUE TITLE
Problem with injecting .NET IOptions<TOptions>

### ISSUE THREAD

**Issue by playing-with-js** [enisn/DotNurseInjector#8]
I'm registering `IOptions<DataAccess>` this way:
```c#
services.Configure<DataAccess>(configuration.GetSection(nameof(DataAccess)));
```

After that I'm getting exception:
```
System.ArgumentException: 'Open generic service type 'Microsoft.Extensions.Options.IOptions`1[TOptions]' requires registering an open generic implementation type. (Parameter 'descriptors')'
```

I saw that u tried to apply fix in related issue: https://github.com/enisn/DotNurseInjector/issues/6. However, it still doesn't work.

**Comment by enisn** [comment]
Hi @stpdeveloping 

Can you try the version v2.4.0 ?

I've configured my entity like that:
![image](https://user-images.githubusercontent.com/23705418/144710311-a368df55-64d4-46ec-9067-46393125d9d9.png)

And, injected by attribute:
![image](https://user-images.githubusercontent.com/23705418/144710295-dae2fe01-6776-4f72-8a93-93fe5acd01c9.png)

**Comment by enisn** [comment]
Also, there is already a test for that situation and it passes

https://github.com/enisn/DotNurseInjector/blob/master/tests/DotNurse.Injector.Tests/ResolvingTests.cs#L43
