### ISSUE TITLE
Recursive register namespace

### ISSUE THREAD

**Issue by azhe403** [enisn/DotNurseInjector#9]
I've a project with structure like a this.

![image](https://user-images.githubusercontent.com/17938038/144631049-2c3c5bc2-6a74-4930-aa48-deb5403b3a42.png)

Can i resolve all below `root.Handlers` and will be recursively register all Childs?

so, I just call with code `services.AddServicesFrom("root.Handlers", ServiceLifetime.Scoped);`

**Comment by enisn** [comment]
Hi @azhe403 

I've just published v2.4 with a feature that allows registering services recursively.

- Update to v2.4.0
- Use the following method at **Startup.cs**
```csharp
services.AddServicesFrom(x => x.Namespace?.StartsWith("root.Handlers") ?? false);
```
_I placed a null check, some of types may don't have a namespace such as AssemblyInfo_

Also you can use Unit Tests as a reference:
https://github.com/enisn/DotNurseInjector/blob/master/tests/DotNurse.Injector.Tests/StartupTests.cs#L177

**Comment by enisn** [comment]
Also, passing assembly parameter improves startup performance sightly, so, if all of your types are in the same assembly, using the following code is much more performant:

```csharp
services.AddServicesFrom(
    x => x.Namespace?.StartsWith("root.Handlers") ?? false, 
    configAction: opts => opts.Assembly = GetType().Assembly);
```

**Comment by azhe403** [comment]
btw, it can load from another main assembly?

I have a `root.Utils` and `root.Handlers`

Can resolve all `root.Handlers` from `root.Utils` ?

**Comment by enisn** [comment]
It's a lambda expression, you can write any logic you want.

Even you can try register all types in your namespace via writing a **StartsWith** rule with your project name:
```csharp
services.AddServicesFrom(
    x => x.Namespace?.StartsWith("YourProjectName") ?? false);
```

If you're not sure about registering all classes from your entire project you can just use an OR rule:

```csharp
services.AddServicesFrom(
    x => x.Namespace != null && (x.Namespace.StartsWith("root.Handlers") || x.Namespace.StartsWith("root.Utils")));
```

**Comment by enisn** [comment]
> Can resolve all `root.Handlers` from `root.Utils` ?

As an answer to your question above, It searches for all assemblies referenced by your main project. So the answer is YES, if you write the rule properly, yes it'll resolve.
You can check the **ITypeExplorer** implementation:
https://github.com/enisn/DotNurseInjector/blob/d89fa6273ed1262dd69b9d1e8a4398877956b5a3/src/DotNurse.Injector/Services/DotNurseTypeExplorer.cs#L42-L64

**Comment by azhe403** [comment]
Oh nice, thanks for these changes. I'm really appreciate!
